param(
    [string]$ReleaseName = "v0.1.0-rc2"
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ExePath = Join-Path $ProjectRoot "dist\NameVerification.exe"
$ReleaseRoot = Join-Path $ProjectRoot "release"
$PackageDir = Join-Path $ReleaseRoot $ReleaseName
$ZipPath = Join-Path $ReleaseRoot ("NameVerification-" + $ReleaseName + "-portable.zip")
$Today = Get-Date -Format "yyyyMMdd"
$ManifestPath = Join-Path $PackageDir ("00_manifest_" + $ReleaseName + "_" + $Today + ".csv")
$ChecksumPath = Join-Path $PackageDir ("70_release_evidence\checksums_sha256_" + $ReleaseName + "_" + $Today + ".txt")
$ValidationPath = Join-Path $PackageDir ("70_release_evidence\validation_log_template_" + $ReleaseName + "_" + $Today + ".txt")

function New-DirIfMissing([string]$Path) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Write-TextFile([string]$Path, [string]$Content) {
    $Parent = Split-Path -Parent $Path
    New-DirIfMissing $Parent
    $Content | Set-Content -Path $Path -Encoding UTF8
}

Write-Host "[1/7] Check EXE exists"
if (-not (Test-Path $ExePath)) {
    throw "EXE not found: $ExePath. Run .\scripts\build_exe_windows.ps1 first."
}

Write-Host "[2/7] Prepare portable release directory"
if (Test-Path $PackageDir) {
    Remove-Item $PackageDir -Recurse -Force
}
New-DirIfMissing $ReleaseRoot
New-DirIfMissing $PackageDir

$Directories = @(
    "00_readme",
    "10_app",
    "20_config",
    "30_prod_db",
    "40_logs",
    "50_backups\daily",
    "50_backups\before_restore",
    "50_backups\before_import",
    "60_exports\csv",
    "60_exports\json",
    "60_exports\sql",
    "70_release_evidence",
    "80_drive_upload",
    "90_docs",
    "99_review"
)
foreach ($Dir in $Directories) {
    New-DirIfMissing (Join-Path $PackageDir $Dir)
}

Write-Host "[3/7] Copy EXE"
Copy-Item $ExePath (Join-Path $PackageDir "10_app\NameVerification.exe") -Force

Write-Host "[4/7] Write portable README files"
Write-TextFile (Join-Path $PackageDir "00_readme\README_起動前に読む.txt") @"
NameVerification portable release: $ReleaseName

起動方法:
1. 10_app\NameVerification.exe を起動する。
2. portable配布では、既定DBは 30_prod_db\nameverification.db です。
3. DB change log は 40_logs\change_logs.jsonl へ出力されます。
4. Operations log は 40_logs\operations_events.jsonl へ出力されます。

注意:
- 署名付きインストーラではありません。
- 初回運用前にバックアップ、Export、Restore/Importの確認手順を実施してください。
- Restore/Import はadmin専用のdestructive操作です。実行前にbefore_restore/before_importへ自動退避されます。
"@

Write-TextFile (Join-Path $PackageDir "10_app\README_アプリ配置.txt") "NameVerification.exe を配置するフォルダです。EXE直起動時は、この親フォルダをportable package rootとして扱います。"
Write-TextFile (Join-Path $PackageDir "30_prod_db\README_実運用DB.txt") "portable配布時の既定DB配置先です。初回起動時に nameverification.db が作成されます。"
Write-TextFile (Join-Path $PackageDir "40_logs\README_ログ.txt") "change_logs.jsonl と operations_events.jsonl の既定出力先です。"
Write-TextFile (Join-Path $PackageDir "50_backups\README_バックアップ.txt") "daily は通常バックアップ、before_restore/before_import はdestructive操作前の自動退避先です。"
Write-TextFile (Join-Path $PackageDir "60_exports\README_エクスポート.txt") "CSV/JSON/SQL dump の既定出力先です。"
Write-TextFile (Join-Path $PackageDir "80_drive_upload\README_Drive配置.txt") "この $ReleaseName フォルダをまとめてGoogle Drive等へ配置する想定です。"
Write-TextFile (Join-Path $PackageDir "99_review\最終見直しレビュー.txt") "release package generated by scripts/package_release_windows.ps1 on $(Get-Date -Format s)."
Write-TextFile $ValidationPath "Validation commands to run before release: pytest -q; ruff check .; black --check .; mypy app; .\scripts\build_exe_windows.ps1; .\scripts\smoke_test_exe_windows.ps1"

Write-Host "[5/7] Create manifest"
$ManifestRows = New-Object System.Collections.Generic.List[string]
$ManifestRows.Add("relative_path,size_bytes,sha256")
$Files = Get-ChildItem -Path $PackageDir -Recurse -File | Sort-Object FullName
foreach ($File in $Files) {
    $RelativePath = $File.FullName.Substring($PackageDir.Length + 1).Replace("\", "/")
    $Hash = (Get-FileHash -Algorithm SHA256 -Path $File.FullName).Hash.ToLowerInvariant()
    $ManifestRows.Add("$RelativePath,$($File.Length),$Hash")
}
$ManifestRows | Set-Content -Path $ManifestPath -Encoding UTF8

Write-Host "[6/7] Create checksum file"
$ChecksumLines = New-Object System.Collections.Generic.List[string]
$Files = Get-ChildItem -Path $PackageDir -Recurse -File | Sort-Object FullName
foreach ($File in $Files) {
    $RelativePath = $File.FullName.Substring($PackageDir.Length + 1).Replace("\", "/")
    $Hash = (Get-FileHash -Algorithm SHA256 -Path $File.FullName).Hash.ToLowerInvariant()
    $ChecksumLines.Add("$Hash  $RelativePath")
}
$ChecksumLines | Set-Content -Path $ChecksumPath -Encoding UTF8

Write-Host "[7/7] Create zip"
if (Test-Path $ZipPath) {
    Remove-Item $ZipPath -Force
}
Compress-Archive -Path $PackageDir -DestinationPath $ZipPath -Force

if (-not (Test-Path $ZipPath)) {
    throw "Release zip was not created: $ZipPath"
}

Write-Host "Release package complete: $ZipPath"
Write-Host "Portable folder: $PackageDir"
Write-Host "Manifest: $ManifestPath"
Write-Host "Checksums: $ChecksumPath"
